---
- name: Install logstash repository
  copy: src=logstash/logstash.repo dest=/etc/yum.repos.d/logstash.repo
  tags:
  - packages
  - logstash

- name: Install logstash
  yum: pkg=logstash state=present
  tags:
  - packages
  - logstash

- name: Install /etc/logstash/logstash.conf
  copy: src=logstash/logstash.conf dest=/etc/logstash/logstash.conf
  notify: Restart logstash
  tags:
  - logstash

- name: Create /etc/logstash subdirectories
  file: dest=/etc/logstash/{{ item }} state=directory
  with_items:
  - patterns
  - templates
  tags:
  - logstash

- name: Create /etc/logstash/tls
  file: dest=/etc/logstash/tls state=directory owner=logstash group=logstash
        mode=0700
  tags:
  - logstash

# openssl req -new -x509 -sha256 -batch -nodes -newkey rsa:4096 -keyout /etc/logstash/tls/private.pem -subj "/CN=sampoong.wuvt.vt.edu" -days 3650 -out /etc/logstash/tls/public.pem -extensions SAN -config <(cat /etc/pki/tls/openssl.cnf <(printf "[SAN]\nbasicConstraints=critical,CA:true,pathlen:0\nkeyUsage=digitalSignature,keyEncipherment,keyCertSign\nsubjectAltName=DNS:sampoong.wuvt.vt.edu,IP:192.168.0.223"))

- name: Install logstash patterns
  copy: src=logstash/patterns/{{ item }} dest=/etc/logstash/patterns/{{ item }}
  with_items:
  - ntp.grok
  - pam.grok
  - postfix.grok
  - selinux.grok
  - sudo.grok
  - uwsgi.grok
  notify: Restart logstash
  tags:
  - logstash

- name: Install logstash elasticsearch templates
  copy: src=logstash/templates/{{ item }}.json
        dest=/etc/logstash/templates/{{ item }}.json
  with_items:
  - cron
  - icecast
  - nginx
  - ntp
  - postfix
  - selinux
  - syslog
  - uwsgi
  - yum
  notify: Restart logstash
  tags:
  - logstash

- name: Install logstash.service
  copy: src=logstash/logstash.service dest=/etc/systemd/system/logstash.service
  tags:
  - services
  - logstash

- name: Open logstash port in firewalld
  firewalld: port=5043/tcp immediate=true permanent=true state=enabled
  when: ansible_distribution_version.split(".")[0] == "7"
  tags:
  - firewalld

- name: Enable and start logstash
  service: name=logstash enabled=yes state=started
  tags:
  - services
  - logstash
